name: Deployment test via Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy-via-tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-actions@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: test bs
        run: |
          ssh -o "StrictHostKeyChecking no" tuunikala@prod-docker-host "
            cd /home/tuunikala
            touch test.txt
          "
